# Generated by Django 5.2.4 on 2025-08-13 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('SPREAD', 'Spread'), ('TOTAL', 'Total'), ('PROP', 'Player Prop')], default='spread', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='parlay_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together={('user', 'season', 'week', 'bet_type')},
        ),
        migrations.CreateModel(
            name='TeamParlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('decimal_odds', models.FloatField(default=1.0)),
                ('stake_units', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost')], default='PENDING', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parlays', to='league.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parlays', to='league.team')),
            ],
            options={
                'unique_together': {('team', 'season', 'week')},
            },
        ),
    ]
