# Generated by Django 5.2.4 on 2025-08-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_alter_bet_unique_together_bet_bet_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('SPREAD', 'Spread'), ('TOTAL', 'Total'), ('PROP', 'Player Prop')], default='spread', max_length=10),
        ),
    ]
