# Generated by Django 5.2.4 on 2025-08-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_bet_bet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='over_under',
            field=models.CharField(blank=True, choices=[('OVER', 'Over'), ('UNDER', 'Under')], help_text='Required for Totals/Player Props; leave empty for Spreads.', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('SPREAD', 'Spread'), ('TOTAL', 'Total'), ('PROP', 'Player Prop')], default='SPREAD', max_length=10),
        ),
        migrations.AlterField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('PUSH', 'Push')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='teamparlay',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('PUSH', 'Push')], default='PENDING', max_length=10),
        ),
    ]
