# Generated by Django 5.2.4 on 2025-08-30 19:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_bet_over_under_alter_bet_bet_type_alter_bet_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturePick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(help_text='1..3')),
                ('pick_text', models.CharField(max_length=255)),
                ('american_odds', models.IntegerField(help_text='e.g., -110, +350')),
                ('stake_units', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('PUSH', 'Push')], default='PENDING', max_length=10)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futures', to='league.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futures', to='league.team')),
            ],
            options={
                'unique_together': {('team', 'season', 'index')},
            },
        ),
    ]
